### ISSUE TITLE
Where's the api key and is the backend opensource?

### ISSUE THREAD

**Issue by shipsywor** [Vaibhav2002/NotesAppCompose#1]
Unresolved reference: APIKEY

Please provide api key or opensource the backend and provide the compilation steps if possible.

**Comment by Vaibhav2002** [comment]
Backend code is there in https://github.com/Vaibhav2002/Spring-Boot-Notes-REST-API, you need to connect backend to your database.

The Api key is custom , u can create any key and just paste it in the app code and the backend code in the correct files. See the code for app and backend , you will understand where u need to paste  the your own API key
